### ISSUE TITLE
incompatibility with fastboard

### ISSUE THREAD

**Issue by goncalodelima** [Tavius7/FulfillSpigot#2]
https://youtu.be/SoHgIaaa3Wk
https://github.com/MrMicky-FR/FastBoard
[scoreboard.zip](https://github.com/user-attachments/files/16736791/scoreboard.zip)

**Comment by Tavius7** [comment]
Thanks for reporting the issue. It works with other plugins which use FastBoard-API, I think there is a issue with your plugin.
You can report this issue again if it still occurs.

Thanks!
